import streamlit as st

class HomePage:
    """
    Class representing the Home page of the Machine Vision Application.
    """

    def __init__(self):
        """Initialize the HomePage instance."""
        self.title = ":camera_with_flash: :rainbow[Machine Vision] :gray[Application] :camera_with_flash:"
        self.welcome_message = "Welcome to our Machine Vision Application! This tool provides various computer vision capabilities."

    def render(self):
        """Render the home page content."""
        st.set_page_config(
            page_title="Fire Machine Vision",
            page_icon=":fire:",
            # layout="wide",
            # initial_sidebar_state="expanded",
            menu_items={
                'Get Help': 'https://www.extremelycoolapp.com/help',
                'Report a bug': "https://www.extremelycoolapp.com/bug",
                'About': "# This is a header. This is an *extremely* cool app!"
            }
        )
        # Display the title and welcome message
        st.title(self.title, anchor=False)
        st.write(self.welcome_message)

        # Render the feature sections
        self._create_feature_layout()

        # Return self to allow chaining
        return self

    def _create_feature_layout(self):
        """Create the three-column layout for features."""
        # Create a three-column layout
        col1, col2 = st.columns(2)
        col3, col4 = st.columns(2)
        # Render the expandable info section
        self._create_info_expander()
        st.divider()
        st.title(":gray[About Our] :rainbow[Team] :wave:", anchor=False)
        col5, col6 = st.columns(2)
        # Configure each feature column
        with col1:
            self._render_feature_section(
                "Face Recognition",
                "resources/OSK.jpg",
                "Detect and recognize faces in images and video streams with converted ONNX model and SVM."
            )
            if st.button("Go to Face Recognition page"):
                st.switch_page("pages/face_recognition.py")

        with col2:
            self._render_feature_section(
                "Object Detection",
                "resources/YOLO__Schreibtisch_mit_Objekten.jpg",
                "Identify and track objects in real-time using YOLO11n and its fruit-ed fine-tuned version."
            )
            if st.button("Go to YOLO page"):
                st.switch_page("pages/objection_yolo.py")

        with col3:
            self._render_feature_section(
                "Image Transformation",
                "resources/digit_proc.png",
                "Digital Image Transformation technique implemented using numpy and OpenCV."
            )
            if st.button("Go to Image Transformation"):
                st.switch_page("pages/digital_processing.py")

        with col4:
            self._render_feature_section(
                "Custom Diffusion Model",
                "https://via.placeholder.com/150",
                "Try out your own custom images generated by diffusion models."
            )
            if st.button("Go to Diffusion Model"):
                pass

        with col5:
            self._render_feature_section(
                "Truong Ngoc Loi",
                "resources/flork.jpeg",
                "Very first member of team."
            )
            st.link_button("Go to this guy Github", "https://github.com/loiturong")

        with col6:
            self._render_feature_section(
                "Truong Ngoc Loi",
                "resources/flork.jpeg",
                "Very second member of team."
            )
            st.link_button("Go to that guy Github", "https://github.com/loiturong")

    def _render_feature_section(self, header_text, image_path, description):
        """Render an individual feature section."""
        st.header(header_text, anchor=False)
        st.image(image_path, use_container_width=True)
        st.write(description)

    def _create_info_expander(self):
        """Create the expandable information section."""
        with st.expander("Learn More About Our Features"):
            st.write("""
            Our application offers state-of-the-art machine vision capabilities:
            - Real-time face detection and recognition
            - Multiple object detection and tracking
            - Image classification using deep learning
            - Custom model training options
            """)


# Function to maintain backward compatibility with Class-Based API
def home():
    """Legacy function that creates and renders the HomePage."""
    home_page = HomePage()
    home_page.render()

if __name__ == "__main__":
    home()